emailFrom: abc@gmail.com
emailTo:
    - abcd@gmail.com
    - abcde@gmail.com
emailSubject: "HelpOp Email Support Request"
emailHost: localhost
smtpUser: ""
smtpPassword: ""
smtpPort: 25
smtpAuth: true
useSSL: true